# Generated by Django 4.0.6 on 2022-07-26 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 26, 20, 1, 57, 94001)),
        ),
    ]
